using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;
using System.Text;
using System.Text.Json;
using ClawMachine.Mechanics;
using UnityEngine.Networking;
static void Run(IEnumerator r){while(r.MoveNext())if(r.Current is IEnumerator nested)Run(nested);}
var auth=new BoothStaffAuth();
typeof(BoothStaffAuth).GetProperty("Instance",BindingFlags.Static|BindingFlags.Public).SetValue(null,auth);
var claims=Convert.ToBase64String(Encoding.UTF8.GetBytes("{\"aud\":\"test-project\",\"boothStaff\":true,\"boothAdmin\":true}")).TrimEnd('=').Replace('+','-').Replace('/','_');
typeof(BoothStaffAuth).GetField("idToken",BindingFlags.Instance|BindingFlags.NonPublic).SetValue(auth,"x."+claims+".x");
typeof(BoothStaffAuth).GetField("tokenExpiresAt",BindingFlags.Instance|BindingFlags.NonPublic).SetValue(auth,1000f);
var service=FirebaseRESTService.Instance;
service.firebaseProjectId="test-project";
var requests=new List<string>();
var stats="{\"updateTime\":\"2026-01-01T00:00:00Z\",\"fields\":{\"totalDolls\":{\"integerValue\":\"1\"},\"totalLegendaryDolls\":{\"integerValue\":\"1\"},\"totalPlays\":{\"integerValue\":\"0\"},\"totalRevenue\":{\"integerValue\":\"0\"},\"totalRegistrations\":{\"integerValue\":\"0\"},\"totalSuccesses\":{\"integerValue\":\"0\"}}}";
var person="{\"name\":\"projects/test-project/databases/(default)/documents/Participants/candidate\",\"updateTime\":\"2026-01-01T00:00:00Z\",\"fields\":{\"insta\":{\"stringValue\":\"candidate\"},\"isPicked\":{\"booleanValue\":false}}}";
UnityWebRequest.Responder=req=>{ if(req.method=="GET"&&req.url.EndsWith("GameState/stats"))return(200,stats); if(req.method=="GET"&&req.url.EndsWith("ParticipantKeys/insta_candidate"))return(200,"{\"fields\":{\"participantKey\":{\"stringValue\":\"candidate\"}}}"); if(req.method=="GET"&&req.url.EndsWith("ParticipantKeys/insta_stale"))return(200,"{\"fields\":{\"participantKey\":{\"stringValue\":\"missing\"}}}"); if(req.method=="GET"&&req.url.EndsWith("Participants/candidate"))return(200,person); if(req.method=="GET")return(404,""); var body=Encoding.UTF8.GetString(req.uploadHandler.bytes); JsonDocument.Parse(body); requests.Add(body); if(req.url.EndsWith(":runQuery"))return(200,"[]"); if(req.url.EndsWith(":runAggregationQuery"))return(200,"[{\"result\":{\"aggregateFields\":{\"count\":{\"integerValue\":\"2\"}}}}]"); return(200,"{}"); };
bool registered=false,prize=false,profile=false,inventory=false;
Run(service.RegisterPlayer("Name","Candidate","Bio","여",0,ok=>registered=ok));
Run(service.CheckInstaIdExists("candidate",exists=>{if(exists!=true)throw new Exception("valid index rejected");}));
Run(service.CheckInstaIdExists("stale",exists=>{if(exists!=null)throw new Exception("stale index accepted");}));
Run(service.ClaimPrize("round1",false,ok=>prize=ok)); Run(service.CheckInstaIdExists("fresh",exists=>{if(exists!=false)throw new Exception("bad duplicate check");})); Run(service.GetRandomMatch("여",match=>{if(match.success)throw new Exception("unexpected match");}));
Run(service.ClaimProfile("round2",new MatchedProfileResponse{documentId="candidate",insta="candidate"},ok=>profile=ok));
Run(service.GetUnpickedCounts((male,female)=>{if(male!=2||female!=2)throw new Exception("bad aggregation: "+male+" "+female);}));
Run(service.UpdateTotalDolls(3,ok=>inventory=ok));
service.IncrementPlayCountAndRevenue(500);
if(!registered||!prize||!profile||!inventory||requests.Count!=8)throw new Exception($"flows: {registered} {prize} {profile} {inventory} {requests.Count}");
Console.WriteLine("Love index/registration/prize/profile/count/inventory/play JSON: 8 valid requests");
